### ISSUE TITLE
Wiki editor setup pages

### ISSUE THREAD

**Issue by blobaugh** [WebDevStudios/WDS-Coding-Standards#25]
It would be nice to have pages on the wiki covering how to set up the coding standards in various editors.

**Comment by aubreypwd** [comment]
This is all going to be in the README on the next release @blobaugh

**Comment by aubreypwd** [comment]
..but it might be worth considering moving this to the wiki, so it's easier to find and fix w/out having to do that via releases ¯\_(ツ)_/¯...

**Comment by aubreypwd** [comment]
It's actually been moved to the wiki (installation instructions) so we can maintain them.
