### ISSUE TITLE
Update CONTRIBUTING.md to add information for how to vote on issues.

### ISSUE THREAD

**Issue by jmichaelward** [WebDevStudios/WDS-Coding-Standards#31]
It's not immediately clear reviewing the document about _how_ devs should vote on merging a PR. Can we add that to the contributing doc so that it's easier to know what to do?

**Comment by jrfoell** [comment]
Created an animation to add:

![wds-coding-standards-voting](https://user-images.githubusercontent.com/630830/31842232-ac59d226-b5b2-11e7-882c-bcff69fdcc31.gif)
