### ISSUE TITLE
WPCS 0.14.0 Compatibility

### ISSUE THREAD

**Issue by jrfoell** [WebDevStudios/WDS-Coding-Standards#34]
Because WDS-Coding-Standards is an extension of WordPress-Coding-Standards, we should review and include their changes in our release cycle. Sometimes we may want to bring back rules that have gone away or alter rules to suit our typical environments.

We should bump our version number when requiring a newer WPCS version so that same WDS-CS versions always produce the same output/result. 

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/0.14.0

**Comment by jmichaelward** [comment]
I second this motion. Now that we're tracking versions of WDSCS, any new releases - regardless of whether they include updates to the WordPress Coding Standards or not - should be tagged with a new version number.

**Comment by aubreypwd** [comment]
> any new releases - regardless of whether they include updates to the WordPress Coding Standards or not - should be tagged with a new version number.

> we should review and include their changes in our release cycle.

@jomurgel @jrfoell 

Our local repository does not _contain_ any WPCS stuff, so it's not really _updated_ with any changes there. Our coding standards, though, are compatible with a certain version of WPCS which you also have to have (as a dependency) cloned down and installed as well. E.g., future version of WPCS _could_ break WDSCS, but that would be totally disconnected from our repo.

...unless I'm not understanding something here. Ping me if you want to get on a ☎️  to discuss in person if I am.

**Comment by aubreypwd** [comment]
We have a 0.14.1 tag now, closing this for the PR @jrfoell submitted.
