### ISSUE TITLE
Add post-install commands to composer.json

### ISSUE THREAD

**Issue by jmichaelward** [WebDevStudios/WDS-Coding-Standards#37]
Now that we have a `composer.json` file attached to this project, devs can install our coding standards on a project level by running `composer require webdevstudios/wds-coding-standards` from the project root, or globally by adding in the `global` keyword after the `require` keyword.

Composer allows for some additional flexibility, as we can define pre- and post- install commands that should run during the installation process. Once such command, post-install, should be to add WDS Coding Standards and WordPress Coding Standards to the PHPCS installed_paths configuration.

Since Composer installs both of these packages to the vendor directory, in theory, we could add something like this to the composer.json file:

```
"scripts": {
    "post-install-cmd": {
        "vendor/bin/phpcs --config-set installed_paths ${PWD}/webdevstudios/wds-coding-standards/WebDevStudios,${PWD}/wds-coding-standards/wpcs"
    }
}
```

That command should run the PHPCS command from the composer install path and add both of the rulesets to PHPCS. Of course, that particular command may not work for global and local, and we may want to do some additional testing to ensure that it doesn't step on other installed paths, such as for client-specific projects. Still, the general idea remains - if we're able to auto-configure PHPCS following installation of WDS Coding Standards, we're one step closer to making this more broadly usable.

**Comment by aubreypwd** [comment]
@jmichaelward I would <3 to see a PR for this :D 

One thing I'm worried about is keeping the user's current `installed_paths` set, e.g. I may have some other standards I want to keep installed. Is there a way to ensure that the current `installed_paths` remain but update WebDevStudios?

**Comment by jmichaelward** [comment]
@aubreypwd I agree - it's something we should look into. I don't know for certain, but I would assume that `phpcs` has a way to spit out the current installed paths. We could set it so that our command only appends these new paths (if they don't already exist) instead of flatly overwriting them.

**Comment by aubreypwd** [comment]
Noting that we need to install eslint, sasslint, and the custom eslint plugin post install here, basically doing as much of the installation process for them post install.

**Comment by aubreypwd** [comment]
Made some [more progress](https://github.com/WebDevStudios/WDS-Coding-Standards/compare/release-next...feature/install-npm) on this and allowing automated installs of es-lint stuff, it's rough right now, but moving along. 

We detect if WDSCS is installed globally (`.composer/*`), if so, then it install npm stuffs (if we can) globally too automatically.

**Comment by aubreypwd** [comment]
This is 100% resolved now that we will be using [php-coding-standards](https://github.com/WebDevStudios/), [js-coding-standards](https://github.com/WebDevStudios/js-coding-standards), [css-coding-standards](https://github.com/WebDevStudios/css-coding-standards) and php-coding-standards, thanks to this, will set your projects standard for you.

Thanks @jmichaelward for all your work on this!
