### ISSUE TITLE
Prettier integration

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Coding-Standards#40]
Per our monthly engineering scrum, I would love to know if we can integrate [Prettier](https://prettier.io) into our workflows at WDS.

**Comment by jomurgel** [comment]
Source: https://prettier.io/

**Comment by jomurgel** [comment]
Setup `.prettierrc` a configuration file with some basics, but having trouble getting VSCode to actually change anything to those specifications. Prettier still works as expected, but not to the configuration.

```
{
	// Perttier.io Config: https://prettier.io/docs/en/options.html
    "useTabs": true, // Indent lines with tabs instead of spaces.
    "printWidth": 80, // Specify the length of line that the printer will wrap on.
    "tabWidth": 4,    // Specify the number of spaces per indentation-level.
    "singleQuote": true, // Use single quotes instead of double quotes.
    /**
     * Print trailing commas wherever possible.
     * Valid options:
     *   - "none" - no trailing commas
     *   - "es5" - trailing commas where valid in ES5 (objects, arrays, etc)
     *   - "all" - trailing commas wherever possible (function arguments)
     */
    "trailingComma": "none",
    /**
     * Do not print spaces between brackets.
     * If true, puts the > of a multi-line jsx element at the end of the last line instead of being
     * alone on the next line
     */
    "jsxBracketSameLine": false,
    /**
     * Specify which parse to use.
     * Valid options:
     *   - "flow"
     *   - "babylon"
     */
    "parser": "babylon",
    /**
     * Do not print semicolons, except at the beginning of lines which may need them.
     * Valid options:
     * - true - add a semicolon at the end of every line
     * - false - only add semicolons at the beginning of lines that may introduce ASI failures
     */
    "noSemi": true,
    /**
     * Add additional logging from prettierrc (not prettier itself).
     * Defaults to false
     * Valid options:
     * - true - enable additional logging
     * - false - disable additional logging
     */
    "rcVerbose": true
}
```

Restarted VSCode and change from YAML to JSON and nothing changes.  Even defaulting to the `.editorconfig` without the `.prettierrc` file doesn't seem to work as expected.  Need to dig into this just a little bit.  

From what I can tell, however, just installing the plugin works aces for js, json, css, scss, jsx, just doesn't follow WDS standards just yet.

**Comment by jomurgel** [comment]
Installing globally and using CLI like this ```prettier --single-quote tab-width-4 --use-tabs --write  /Desktop/test.scss
public_html/test.scss``` formats as expected. Even running ```prettier --write /Desktop/test.scss```

I'm guessing something is not set up as expected still, though I have an idea.  Will have to come back to this when I have a free minute.

Off topic, found this, worth looking at with all the additional config files https://blog.cloudboost.io/death-by-thousand-config-files-e23d12367fd9

**Comment by jomurgel** [comment]
Issued PR: https://github.com/WebDevStudios/WDS-Coding-Standards/pull/43
