### ISSUE TITLE
sass lint ignores _colors.scss

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/WDS-Coding-Standards#45]
@coreymcollins  and I were talking about how I didn't get any hex notation (lowecase hex values) error for _colors.scss locally while working on the test project.

It works for him but not me. It turned out that _colors.scss is actually ignored file which is why I wasn't getting any uppercase notation warning.

https://github.com/WebDevStudios/WDS-Coding-Standards/blob/b67302735186a107ec52fefc14dfe5cd3de44cfa/WebDevStudios/.sass-lint.yml#L16

It is strange that warnings did show up for @coreymcollins for the same config file but not me.

Can anyone else replicate this issue?

**Comment by michealengland** [comment]
### DESCRIPTION ###
I tried replicating the issue and found that the hex notations worked as expected. I also tried out other variations of colors values.

<img width="911" alt="Screen Shot 2019-05-09 at 7 13 32 PM" src="https://user-images.githubusercontent.com/25035900/57492432-c8b8fd80-728e-11e9-8827-39e7e5b77aae.png">

**Comment by aubreypwd** [comment]
This will continue https://github.com/WebDevStudios/css-coding-standards/issues/5
