### ISSUE TITLE
Add @author rule

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Coding-Standards#5]
This is going to require some discussion, as currently we use this format:

```
@author Aubrey Portwood, Jay Wood
```

This format was decided on in a previous call, but other formats (more proper formats have been suggested), like:

```
@author Aubrey Portwood
@author Jay Wood
```

I'm going to add the current rule, but please discuss the format below.

**Comment by jmichaelward** [comment]
@aubreypwd I prefer the latter, and also to include the author's e-mail address in brackets after the author's name.

**Comment by aubreypwd** [comment]
Since this is being debated actively, going to punt to a future release.

**Comment by jrfoell** [comment]
I also like multiple @author lines:

```
@author Kellen Mace
@author Justin Foell
```

**Comment by aubreypwd** [comment]
> “Real artists sign their work”

**Comment by aubreypwd** [comment]
What I've done is just required `@author`; due to the complexity of how we use this project to project I did not enforce a format. Also, just a warning.

![](http://aubrey.pw/d/2018/85Q7vQXF4M.png)
