### ISSUE TITLE
WPCS v2.0.0-RC1 Compatability

### ISSUE THREAD

**Issue by phatsk** [WebDevStudios/WDS-Coding-Standards#60]
WDSCS is far behind the current version of WPCS. This task aims to bring the current WDSCS more in-line with version 2.0.0-RC1 of WPCS. 

It may be worth keeping this open until the release candidates are finalized, however, starting work on it now should be fine since the code is in RC. I'm hoping that minimal changes will be needed once a final version is tagged.

**Comment by aubreypwd** [comment]
I have a note on https://github.com/WebDevStudios/WDS-Coding-Standards/pull/61 about it working with our sniffs on `release-1.2`.

**Comment by aubreypwd** [comment]
Note that I'm not sure how I feel about using an RC officially. Maybe when it comes out, maybe this could be slated for a later version? Either way `1.2.1` is the latest stable version and for our `1.2` release I have updated to at least that.

**Comment by aubreypwd** [comment]
Was resolved in https://github.com/WebDevStudios/WDS-Coding-Standards/commit/a210b73cd46ce76d4cfbd8eea578d4b4c3d7eab3 and will go out in 2.0.0
