### ISSUE TITLE
Install sasslint and eslint via npm?

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Coding-Standards#63]
Like I did with #62 we can now run WDSCS own specific version of `phpcs`. I think we can do the same for sasslint and eslint. This way we don't have to use globally installed versions that may or may not conflict depending on how the user updates them on their system.

I do _not_ claim to know how this might work. I mentioned npm because I'm assuming that's a way to install it. But if it could install eslint and sasslint in e.g. `node_modules` and we can run eslint and sasslint from there (that should be installed at specific versions) then we can ensure that phpcs, eslint, and sasslint are all running the versions we expect to work.

**Comment by aubreypwd** [comment]
Also we should update documentation so that people know to configure editors to use our installed versions.

**Comment by aubreypwd** [comment]
Keep in mind that we install this package via composer. I wonder if we could do something like #37 to run `npm install` (or whatever variant we use for sasslint or eslint).

**Comment by aubreypwd** [comment]
Puntint to later release.

**Comment by gregrickaby** [comment]
We could publish our linting files to https://npmjs.org. I could help getting those published, if you'd like?

**Comment by aubreypwd** [comment]
hmm that could be an option. I know right now we just install the package locally, which also works. I think in #37 we would just do the `npm install -g ....` for them as a post install operation. But, if we need this as an option I will keep it in mind!

**Comment by aubreypwd** [comment]
See [js-coding-standards](https://github.com/WebDevStudios/js-coding-standards) and [css-coding-standards](https://github.com/WebDevStudios/css-coding-standards).
