### ISSUE TITLE
PHP Coding Standard Changes on 7/12

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Coding-Standards#78]
[These coding standard changes were noted](https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/) on make with some controversial items.
__________

Please discuss below so a consensus can be reached in preparation for these updates.

_________

Continued discussion from [WDS Slack ](https://webdevstudios.slack.com/archives/C1640HA5S/p1563552031101300)

**Comment by phatsk** [comment]
> Damn, here we go again
- Yeezy

## Closures (Anonymous Functions)
> There was quite a lot of discussion around this proposal, particularly with regards to allowing closures as hook callbacks. Thank you everyone for your input, and for keeping disagreements respectful. 🙂

> We do need a decision, however, and there were several key points that led to this:

> It’s currently difficult to remove closures as hook callbacks. #46635 has several interesting proposals to address this in an entirely backward compatible manner.
> While WordPress Core should strive to allow any callback to be unhooked, plugins have no such restriction.
> The WordPress JavaScript Coding Standards allow for closures to be used, we should be aiming to bring the PHP standards in line with that.
> The broader PHP world has embraced closures for many years, and have found ways to use them responsibly. We shouldn’t ignore PHP usage outside of WordPress.
> With these points in mind, a conservative, but practical step is to allow closures as function callbacks, but not as hook callbacks in Core. Ultimately, we should be able to allow any sort of complex callback to be attached to hooks, but the Core APIs aren’t quite ready for it yet.

### Coding Standards Change
> Where appropriate, closures may be used as an alternative to creating new functions to pass as callbacks.

> Closures must not be passed as filter or action callbacks, as they cannot be removed by remove_action() / remove_filter() (see #46635 for a proposal to address this).

I agree with this for the most part - I think if your callback closure gets too complex (over even 3-4 lines), it's probably a candidate for a standalone method. I'm not going to be a fan of 10-line `array_filter` callbacks ;)

## Short Array Syntax
> A little less controversial, but still with varying opinions, was the proposal to require short array syntax ( `[ 1, 2, 3 ]` ) instead of long array syntax ( `array( 1, 2, 3 )` ) for declaring arrays.

> While I’m personally partial to short array syntax, there were two particularly convincing arguments for using long array syntax:

> It’s easier to distinguish from other forms of braces, particularly for those with vision difficulties.
> It’s much more descriptive for beginners.
> So, this change to the coding standards is the opposite of what was originally proposed, but is ultimately the more inclusive option.

### Coding Standards Change
> Arrays must be declared using long array syntax in WordPress Core.

I vote that we continue to encourage short syntax `[ 1, 2, 4 ]`, in stark contrast with WP's core standards.

## Short Ternary Operator
> The original proposal was to allow the short ternary operator, but this change reverses that. There’s a good argument that it looks too much like the null coalesce operator, especially as they perform different functions.

> Take the following example from Core:

```php
$height = isset( $data['height'] ) ? $data['height'] : 0;
```
> It’s not possible to reduce this line with the short ternary operator, but it can be trivially reduced with the null coalesce operator:

```php
$height = $data['height'] ?? 0;
```
> The vast majority of other ternary operators in Core (which don’t have an isset() test) look something like this:

```php
$class = $thumb ? ' class="has-media-icon"' : '';
```
> This also can’t be reduced using the short ternary operator.

> As the null coalesce operator is a useful addition (which we’ll be able to use once the minimum PHP version bumps to 7+), whereas the short ternary operator can only be used in a handful of cases in Core, it’s better to avoid the potential confusion, and not use the short ternary operator.

### Coding Standards Change
> The short ternary operator must not be used.

I disagree for our own standards. I love Elvis `?:` 

## Assignments Within Conditionals
> Particularly when there are multiple conditions, it can be quite difficult to spot assignments occurring in a conditional. This arguably falls under the Clever Code guidelines, but hasn’t been formalised.

> I got a little ahead of myself with this one, and have already removed all assignments in conditionals from Core. Adding this change to the standard formalises the practice.

### Coding Standards Change
> Assignments within conditionals must not be used.

Strongly agree - this is just asking for trouble:

```php
if ( ! empty( $arr['something'] ) && $someval = $arr['something'] ) {
```

**Comment by oddevan** [comment]
I'm going to agree with @phatsk here:

- Closures: **Agree,** use where appropriate.
- Short Array Syntax: **Disagree for WDS,** we have enough syntax highlighting and code sniffing that the downsides listed by WP are mitigated.
- Short Ternary Operator: Honestly, I don't think I've ever used this. No opinion.
- Assignments Within Conditionals: **Agree**, this looks too easy to abuse.

**Comment by tommcfarlin** [comment]
## Closures

I'd like support for them but there's a proper time and a place to use them and having a guiding rule in place for them would be helpful. 

For example, something like this:

* I think of them like function variables:  If they are only going to be used once and won't need to be debugged outside of a hooked function (or similar situation), then use them; otherwise, don't.

## Short Array Syntax

We know `[]` represents an array. It cannot represent anything else. Let's have support for `[]`.

## Short Ternary Operators (And All Variations)

I want support for them in WDS.

* They read like an English question (almost quite literally with the `?` at the end) and the two possible answers
* The shorthand variations are slightly less easy to read but using them once (that is `??` and `?:`) generally shows how it works. And it condenses code into the same thing as a block but in less space.

## Assignments Within Conditionals

No. A conditional should be used to evaluate an expression, not to do more than one thing (specifically evaluate _and_ assign).

**Comment by aubreypwd** [comment]
Please continue any discussion https://github.com/WebDevStudios/php-coding-standards/issues/9
