### ISSUE TITLE
Add "type" : "phpcodesniffer-standard" to composer.json

### ISSUE THREAD

**Issue by jrfoell** [WebDevStudios/WDS-Coding-Standards#80]
This would allow another composer package https://github.com/Dealerdirect/phpcodesniffer-composer-installer to automatically set the config path for PHPCS to include WDSCS. I can submit a PR if you'd like.

**Comment by aubreypwd** [comment]
This is already a feature in [php-coding-standards](https://github.com/WebDevStudios/php-coding-standards)...
